language: node_js
node_js:
  - "8"
services:
  - elasticsearch
#small delay to make sure that Elasticsearch is available
before_script:
  - sleep 10
  - npm install coveralls --save-dev
after_script:
  - nyc report --reporter=text-lcov | coveralls