language: node_js
node_js:
  - "8"
services:
  - elasticsearch
#small delay to make sure that Elasticsearch is available
before_script:
  - sleep 5
  - npm install coveralls --save-dev
script:
  - nyc npm test && nyc report --reporter=text-lcov | coveralls